In [1]:
import numpy as np
import pandas as pd

data = {
    "Name": ["Mayank", "Himanshu", "Karan", "Rahul", "Aman", "Vikas"],
    "Age": [20, 22, np.nan, 25, 21, 18],
    "City": ["Delhi", "Mumbai", "Pune", np.nan, "Jaipur", "Dehradun"],
    "Salary": [50000, 60000, 45000, 70000, np.nan, 40000]
}

df = pd.DataFrame(data)
df

       Name   Age      City   Salary
0    Mayank  20.0     Delhi  50000.0
1  Himanshu  22.0    Mumbai  60000.0
2     Karan   NaN      Pune  45000.0
3     Rahul  25.0       NaN  70000.0
4      Aman  21.0    Jaipur      NaN
5     Vikas  18.0  Dehradun  40000.0

In [ ]:
#to check whether Nan values is there in it 

df.isna() #wherever nan will be there it will give true otherwise false

    Name    Age   City  Salary
0  False  False  False   False
1  False  False  False   False
2  False   True  False   False
3  False  False   True   False
4  False  False  False    True
5  False  False  False   False

In [ ]:
# total nan in each column.
df.isna().sum()

Name      0
Age       1
City      1
Salary    1
dtype: int64

In [ ]:
# to check whether each column  contain nan value the column with no nan value will give false.

df.isna().any()

Name      False
Age        True
City       True
Salary     True
dtype: bool