In [7]:
# Joining Two data frames

import numpy as np
import pandas as pd



df1 = pd.DataFrame({
    "Name": ["Mayank", "Himanshu", "Karan", "Rahul"]
}, index=[1, 2, 3, 4])

df2 = pd.DataFrame({
    "Score": [78, 92, 85, 88]
}, index=[3, 4, 5, 6])


df1

       Name
1    Mayank
2  Himanshu
3     Karan
4     Rahul

In [8]:
df2

   Score
3     78
4     92
5     85
6     88

In [ ]:
# BY default join (how is always inner)

df1.join(df2 , how='inner')

# if df2.join(df1.join) was written then score will come ahead in the table.

    Name  Score
3  Karan     78
4  Rahul     92

In [10]:
# Outer join 

df1.join(df2,how='outer')

       Name  Score
1    Mayank    NaN
2  Himanshu    NaN
3     Karan   78.0
4     Rahul   92.0
5       NaN   85.0
6       NaN   88.0